### ISSUE TITLE
Springboard crashes when using Lynx 2 when disabling widget names

### ISSUE THREAD

**Issue by AdamCraftmaster** [ryannair05/Cylinder-Reborn#3]
---
name: Cylinder Reborn Bug Report
about: Scrolling crashes with Lynx 2
labels: bug

---

**Describe the bug**
When using Cylinder Reborn and Lynx 2 with widget names disabled, swiping quickly on the home screen causes a springboard crash into safe mode.

**To Reproduce**
Install both Lynx 2 and Cylinder Reborn.
Open Lynx 2 settings.
Enable Lynx 2.
Open widgets category.
Enable "Hide Labels on Homescreen".
Respring device.
Open and close widget app.
Swipe left and right quickly.
Springboard should crash

**Screenshots**
![image](https://user-images.githubusercontent.com/64713401/109837829-9458c300-7c13-11eb-934e-4cdfad50b17e.png)

Crash logs: https://paste.ee/p/S9jjk

**Platform (please complete the following information):**
 - Device: (iPhone 11 Pro)
 - Injection: (Unc0ver, substrate)
 - iOS Version: (iOS 14.3)
 - Package Manager: (Zebra)

**Comment by AdamCraftmaster** [comment]
The issue seems to also happen when opening any app, closing it, and quickly swiping.

**Comment by Silentoplayz** [comment]
I can confirm what @AdamCraftmaster has said is to be mostly true, but I’d like to add onto this bug report with my own tested/tried and true information.

With the bug reported, swiping over to the App Library or Today View after swiping out of an application to the Home Screen, won’t crash your device into Safe Mode. Your device will only crash into Safe Mode if swiping left or right to another page with applications on it.

It is not just opening a widget and the steps followed to crash into safe mode in itself. This happens with any application I’ve tested to replicate the bug.

I can’t necessarily say that Lynx 2 is conflicting with Cylinder Reborn, because Cr4shed crash logs tell us that it’s Cylinder Reborn as the culprit.

This bug occurs and can be replicated 100% of the time (if steps provided by @AdamCraftmaster are followed correctly) on my iPhone XR running iOS 14.3 jailbroken with unc0ver v6.0.1

**Comment by MTACS** [comment]
Fixed in Lynx 2.0.4, added check for nil widget name that would sometimes be returned

**Comment by AdamCraftmaster** [comment]
> Fixed in Lynx 2.0.4, added check for nil widget name that would sometimes be returned

Thank you, will check if it works. Thanks for the good work on Lynx!

**Comment by MTACS** [comment]
No problem, the update will be live in a few days, apologies for crashes until then

**Comment by Saravia83c** [comment]
🤔🤔

**Comment by AdamCraftmaster** [comment]
Fixed in Lynx 2.0.4

**Comment by Saravia83c** [comment]
@Haha
